### ISSUE TITLE
Test Version 3 of the API

### ISSUE THREAD

**Issue by crookedneighbor** [fplourde/Taskwarrior-habitica-hooks#1]
We're looking for Habitica developers to try out the upcoming version 3 of the API. We are hoping that we will be ready to start testing within the next two weeks, but we're collecting testers now so that we can hit the ground running. Thanks very much for considering it, and feel free to let me know if you have any questions!

| [Sign Up!](https://docs.google.com/forms/d/1xXxZvSviR_s8K3I31bKXH6Dfc6Ud9TuTG66I90PdwQI/viewform) |
| --- |

**Comment by crookedneighbor** [comment]
Just letting you know that the testing phase is now over. Version 2 of the Habitica API will be officially [deactivated on July 15th](http://devs.habitica.com/api-v2-deprecation-notice/). 

[Here is a migration guide](http://devs.habitica.com/api-v2-v3-migration-guide/) for upgrading to version 3. If you have any questions, feel free to reach out on [Github](https://github.com/HabitRPG/habitrpg/issues) or the [Aspiring Comrades Guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e).

**Comment by fplourde** [comment]
Thanks for the headsup. I'll probably update my hooks.
