### ISSUE TITLE
Uses v2

### ISSUE THREAD

**Issue by LordVladneutral** [fplourde/Taskwarrior-habitica-hooks#2]
It uses the api v2 so it is outdated. Sadly.

**Comment by fplourde** [comment]
Hi LordVladneutral,

I do not have the time to put the necessary effort on this project to upgrade the API to version 3 right now. 

However, if you have some time to share, any pull request is welcome.

Have a nice day

**Comment by LordVladneutral** [comment]
I have a little time but I lack skills, so never mind. If you do update it, one day, I'll use it, but until then, I'll stick to habash, it does the job of making the game command line usable.

Have a nice day too.
