### ISSUE TITLE
Not able to use taskwarrior when not connected to the internet

### ISSUE THREAD

**Issue by tassos** [fplourde/Taskwarrior-habitica-hooks#6]
The current implementation of the hooks, does not allow to use taskwarrior when there is no internet connectivity, since the hooks fail if they cannot communicate with the habitica server. Also, even though there is a timeout for the post request in the on-modify hook, this is not present in the on-add hook.

I tried to solve this issue and you can see the solution in my forked repository (https://github.com/tassos/Taskwarrior-habitica-hooks/commit/ca53267c38e56df59279a114c84263e49556f43d and https://github.com/tassos/Taskwarrior-habitica-hooks/commit/be661a836d08173757fa90651173e4f3f3f49bc0). However, before submitting a pull request, I wanted to discuss a bit the desired behaviour.

My implementation is as follows:

When there is internet connectivity:

Everything works normal: a task is added/completed in habitica when it is added/completed in taskwarrior

When there is no internet connectivity:

A task is added in taskwarrior, but not in habitica (as there is no connectivity). The task does not receive a 'habitica_id' key in its JSON, and therefore can be completed without internet connectivity.

When a task with a 'habitica_id' key in its JSON is completed in taskwarrior, the hook allows the task to be completed locally, but not on habitica (since it cannot communicate with habitica). Another alternative would be to not allow the completion of the task locally either, and wait until the user connects to the internet.

I somehow prefer the first option for the modification, as it allows the user to use taskwarrior normally even without an internet connection. However, I can be convinced that the second option is preferred.

What do you think?

**Comment by engines-wafu** [comment]
This seems like a great function to add.

On Tue, Apr 18, 2017 at 07:15:16AM -0700, Tassos Natsakis wrote:
> When there is no internet connectivity:
> 
> A task is added in taskwarrior, but not in habitica (as there is no connectivity). The task does not receive a 'habitica_id' key in its JSON, and therefore can be completed without internet connectivity.
> 
> When a task with a 'habitica_id' key in its JSON is completed in taskwarrior, the hook allows the task to be completed locally, but not on habitica (since it cannot communicate with habitica). Another alternative would be to not allow the completion of the task locally either, and wait until the user connects to the internet.
> 
> I somehow prefer the first option for the modification, as it allows the user to use taskwarrior normally even without an internet connection. However, I can be convinced that the second option is preferred.
> 
> What do you think?

Option 2 seems like a non-starter for my particular workflow as I
often have to work off-line and taskwarrior has primacy for me.

As a thought, is there a way of using the same mechanisms in place for
task sync?

-- 
Regards,

Gavin

G R Edwards
BEng(Hons) MSc CEng CMgr MIET MCMI

+1 571 599 9517

**Comment by fplourde** [comment]
@tassos, I prefer option 1 too. We could add a feedback to warn the user about the task not synced without interrupting his workflow. 

> A hook script may exit with a zero status which signals that all is well. A tasks emitted will be added/modified, and *any feedback will be shown as a footnote*

Adding a task is more important than syncing it.

Thanks for your support

@gavinedwards , what are you suggesting for a mechanism for task sync? Sync unsynced Taskwarrior tasks to Habitica?

The easiest solution would be to update tasks when task are modified locally. Updated local task would be synced with Habitica using the `on-modify` hook.

Did I get your request right?

**Comment by tassos** [comment]
@gavinedwards I totally agree that taskwarrior has primacy, and I guess that is the case for most users. So I will make the pull request like this.

@fplourde Yes, I implemented a feedback that states the task was not synced with Habitica, if the post request fails for a reason.

Regarding the syncing with habitica, unfortunately there is no on-sync hook implemented in taskwarrior, therefore you could only do it when you are modifying a task, as @fplourde mentions.

**Comment by engines-wafu** [comment]
> @gavinedwards I totally agree that taskwarrior has primacy, and I guess that is the case for most users. So I will make the pull request like this.

Okay, that works well for me!

> @fplourde Yes, I implemented a feedback that states the task was not synced with Habitica, if the post request fails for a reason.
> 
> Regarding the syncing with habitica, unfortunately there is no on-sync hook implemented in taskwarrior, therefore you could only do it when you are modifying a task, as @fplourde mentions.

Ah, that was the mechanism I had in mind, so I guess disregard my
last.

-- 
Regards,

Gavin

G R Edwards
BEng(Hons) MSc CEng CMgr MIET MCMI

+1 571 599 9517
